name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -lah 
      - run: pip -V
      - run: python --version
      - run: python -m pip install -U numpy
      - run: python -c "import numpy; print(numpy.version.version)"