name: action_tester

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: python -m pip install --upgrade pip
      - run: pwd
      - run: ls -lah 
      - run: |
          cd ..
          ls -lah
          mkdir secret-finder
          cd secret-finder
          pwd
          wget https://github.com/MiroslavZ/code_scanner/archive/refs/heads/master.zip
          unzip master.zip
          ls -lah
          cd code_scanner-master
          ls -lah
      - run: wget https://github.com/MiroslavZ/code_scanner/archive/refs/heads/master.zip
      - run: pwd
      - run: ls -lah
      - run: unzip master.zip
      - run: |
          cd code_scanner-master
          ls -lah
          pwd
          cd ..
          ls -lah
          pwd
