name: action_tester

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -lah 
      - run: |
          cd ..
          ls -lah
          mkdir secret-finder
          cd secret-finder
          pwd
          wget https://github.com/MiroslavZ/code_scanner/archive/refs/heads/master.zip
          unzip master.zip
          ls -lah
          cd code_scanner-master
          ls -lah
      - run: python -m pip install --upgrade pip
      - run: pip install -r /home/runner/work/actions_test/secret-finder/code_scanner-master/requirements.txt
      - run: |
          cd ..
          cd secret-finder
          ls -lah
          cd code_scanner-master
          ls -lah
          cd code_scanner
          ls -lah
      - run: python3 /home/runner/work/actions_test/secret-finder/code_scanner-master/code_scanner/main.py -s /home/runner/work/actions_test/actions_test

