name: action_tester

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -lah 
      - run: pip -V
      - run: python --version
