name: action_tester

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -lah 
      - run: |
          chmod a+x script.sh
          ./script.sh
      - run: |
          cd ..
          ls -lah
          mkdir secret_finder
          cd secret_finder
          pwd
          wget https://github.com/MiroslavZ/code_scanner/archive/refs/heads/master.zip
          unzip master.zip
          ls -lah
          cd code_scanner-master
          ls -lah
      - run: python -m pip install --upgrade pip
      - run: pip install -r /home/runner/work/actions_test/secret_finder/code_scanner-master/requirements.txt
      - run: |
          cd ..
          cd secret_finder
          ls -lah
          cd code_scanner-master
          ls -lah
          cd code_scanner
          ls -lah
          cd pretrained
          pwd
          ls -lah
      - run: pip install -e /home/runner/work/actions_test/secret_finder/code_scanner-master
      - run: code-scanner --scan-dir $(pwd)
