name: action_tester

on: push

jobs:
  build:
    name: Code scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloading code_scanner
        run: |
          cd ..
          ls -lah
          mkdir secret_finder
          cd secret_finder
          pwd
          wget https://github.com/MiroslavZ/code_scanner/archive/refs/heads/master.zip
          unzip master.zip
          ls -lah
          cd code_scanner-master
          ls -lah
      - name: Upgrading pip and installing libraries from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r /home/runner/work/actions_test/secret_finder/code_scanner-master/requirements.txt
      - name: Installing code_scanner
        run: pip install -e /home/runner/work/actions_test/secret_finder/code_scanner-master
      - name: Scanning the repo
        run: code-scanner --scan-dir $(pwd)
